keys:
  - &j age1t2sjag8q5ndp6g6hmq7h5xg4swum97nt9p7ackfph6z8ceekhpxshaxwlm

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - age1t2sjag8q5ndp6g6hmq7h5xg4swum97nt9p7ackfph6z8ceekhpxshaxwlm

# keys:
#   - &admin_alice 2504791468b153b8a3963cc97ba53d1919c5dfd4
#   - &admin_bob age12zlz6lvcdk6eqaewfylg35w0syh58sm7gh53q5vvn7hd7c6nngyseftjxl
# creation_rules:
#   - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
#     key_groups:
#     - pgp:
#       - *admin_alice
#       age:
#       - *admin_bob